stages:
  - build

.cache-paths: &cache-paths
  paths:
    - _ccache/

meson-fedora-x86_64:
  image: registry.gitlab.gnome.org/gnome/clutter/master:v2
  stage: build
  script:
    - bash -x ./.gitlab-ci/test-docker.sh
  artifacts:
    when: on_failure
    name: "clutter-${CI_COMMIT_REF_NAME}"
    paths:
      - "${CI_PROJECT_DIR}/_build/meson-logs"
  cache:
    key: "$CI_JOB_NAME"
    <<: *cache-paths
