#!/bin/sh
# autopkgtest check: Run the installed-tests to verify clutter works correctly
# (C) 2013 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>

set -eu

export XDG_RUNTIME_DIR="$AUTOPKGTEST_TMP"

dbus-run-session -- xvfb-run -a gnome-desktop-testing-runner clutter
