#!/bin/sh
# autopkgtest check: Run the installed-tests to verify clutter works correctly
# (C) 2013 Canonical Ltd.
# Author: Iain Lane <iain.lane@canonical.com>

set -e

export XDG_RUNTIME_DIR=$ADTTMP

dbus-run-session -- xvfb-run gnome-desktop-testing-runner clutter
